### ISSUE TITLE
Unable to exit OBS Studio via system tray, if window was never visible

### ISSUE THREAD

**Issue by PancakeTAS** [obsproject/obs-studio#10933]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/BVf81EABokxXeG4w

### Expected Behavior

When launching OBS directly into systray, opening the tray menu and selecting "Exit" should exit OBS.

### Current Behavior

Instead, nothing at all happened.

### Steps to Reproduce

1. Run with `--minimize-to-tray` or check the option in the UI
2. Open the tray menu and select `Exit`

### Anything else we should know?

I was able to verify this behavior in Safe Mode as well (so none of my plugins are causing this issue).
If the window was ever visible (even if hidden again) the button will work as intended.

(window manager is i3)

**Comment by mihawk90** [comment]
Can't reproduce this on Plasma 5

**Comment by domoaligato** [comment]
This is a year+ old bug. This still happens to me on Manjaro with KDE Plasma 6.3.6, wayland 1.23.1-2, and OBS 31.0.4

**Comment by ruro** [comment]
This is an extremely annoying bug, because it also breaks exiting via Ctrl+C / SIGINT.

I am trying to create a script that would

1) start obs
2) start recording
3) wait until some custom condition
4) stop recording 
5) gracefully exit obs (so that it doesn't complain about not being shut down improperly on next launch)

and all of that without showing or requiring interaction with a GUI.

This is 99% possible, but this bug is preventing it from actually working. 1-2 can be achieved via `obs --minimize-to-tray --startrecording`. 4 can be achieved via `obs-websockets` and `obs-cmd`. And 5 can be achieved by sending a SIGINT to the process we started in step 1.

Except that this doesn't actually work because `--minimize-to-tray` breaks `Exit`/`SIGINT` handling.

As far as I can tell, the only way to work around this issue is to NOT use `--minimize-to-tray`, but then to minimize the window after it starts using some other way (Window Rules and `xdotool` automation are probably the most sensible options).

UGH! &lt;/rant&gt;

**Comment by zorbathut** [comment]
I dug around on this a bit, and the issue *seems* to be that `OBSBasic::close()` directly calls `OBSMainWindow::close()`, but if the OBS Main Window has never been displayed, Qt silently ignores it. This is the point where my limited knowledge of Qt ran out and I failed to find a good solution. Maybe this will help someone with more knowledge of Qt.

**Comment by BenJuan26** [comment]
Could this have been introduced by my PR here? https://github.com/obsproject/obs-studio/pull/9229

I just closed [this one](https://github.com/obsproject/obs-studio/pull/8889) as unnecessary because I confirmed that OBS (when started normally, with a main window) can be closed with `taskkill` and it no longer leaves dangling resources. What I didn't realize, though, is that it's not possible to do that same action when starting OBS minimized, which was the whole point of my use case.

**Comment by Warchamp7** [comment]
I think this was already fixed by our other recent shutdown changes. I can't reproduce on 32.1

**Comment by zorbathut** [comment]
I *can* still reproduce this on 32.1.2, for the record. I don't know what else I'm doing to cause this, but it's still happening for me.

**Comment by Warchamp7** [comment]
> I _can_ still reproduce this on 32.1.2, for the record. I don't know what else I'm doing to cause this, but it's still happening for me.

Can you open a new issue and include a log file + crash log?

**Comment by zorbathut** [comment]
Done.
