### ISSUE TITLE
c2b482307599 (linux-pipewire: Add explicit sync support, 2024-10-24) causes deadlock

### ISSUE THREAD

**Issue by xtexx** [obsproject/obs-studio#12443]
### Operating System Info

Other

### Other OS

AOSC OS

### OBS Studio Version

31.1.1

### OBS Studio Version (Other)

c2b482307599 (linux-pipewire: Add explicit sync support, 2024-10-24)

### OBS Studio Log URL

https://obsproject.com/logs/DnSvbaz8bZeOz33S

### Expected Behavior

OBS freezes after selecting the screen to capture.

### Current Behavior

It should work.

### Steps to Reproduce

1. Add a PipeWire Screen Capture.
2. OBS freezes after I selecting the screen, not responding.

### Anything else we should know?

Manual bisection points to c2b482307599 (linux-pipewire: Add explicit sync support, 2024-10-24).

My system is AOSC OS (12.2.1), Wayland, KDE Plasma 6.4.3, Qt 6.8.2.

**Comment by tytan652** [comment]
Fixed by #12411

**Comment by xtexx** [comment]
However it still show up in 7778070cbd8e (libobs: Update version to 31.1.2, 2025-07-25) and in the 31.1.2 distributed by AOSC OS. (:

**Comment by xtexx** [comment]
@tytan652 Hi. I can confirm that this still appears in 2b613f40b472 (media-playback: Fix null pointer dereference, 2025-06-16). Could we re-open this issue?
