### ISSUE TITLE
Dynamic Bitrate breaks the Automatically Reconnect feature

### ISSUE THREAD

**Issue by NightmareVortex** [obsproject/obs-studio#2496]
I've been having issues for a long time everytime my stream gets disconnected it won't automatically reconnect, of course I made sure the feature is enabled and I tried setting different time intervals like 5 seconds, or 10 seconds, etc. Nothing, it never reconnects unless I close OBS... And my connection is always fine, it just seems to disconnect sometimes randomly, but it could totally reconnect.

After investigating further and installing the latest OBS RC Candidate that fixes the following bug I thought it could had been that but no luck either:
"Fixed a bug where a reconnected stream would drop to 0 kbps and disconnect if using audio track 2 [R1CH]"

I found out after testing more throughly that enabling Dynamic Bitrate makes this happen after all, and disabling it fixes the problems, but doesn't allow me to use the Dynamic Bitrate that I also been loving so far.

## Expected Behavior

OBS should inmediately reconnect if the bitrate gets to 0KBPS.

## Current Behavior

OBS should inmediately reconnect if the bitrate gets to 0KBPS but it never does, it always gets stuck.

## Steps to Reproduce

1. Enable Dynamic Bitrate
2. Enable Automatically Reconnect at any seconds, it doesn't affect or fix the problem
3. Stream a long session until the bitrate starts going lower than 1000KBPS
4. When OBS shows the stream at 0kbps it doesn't properly disconnect the stream and it's always stuck there, the notification of the stream disconnection doesn't work either and thus reconnecting is impossible

**Comment by theyuvalshor** [comment]
Can confirm I've had this exact issue when dynamic bitrate has been introduced (during the version 24 beta testing).

**Comment by djsavta** [comment]
Can confirm this has happened to me back when dynamic bitrate has been introduced .

**Comment by djsavta** [comment]
Can confirm this has happened to me back when dynamic bitrate was introduced.

**Comment by PatTheMav** [comment]
@NightmareVortex please attach a the OBS log file of a session in which your issue occurred.

**Comment by eFFecTM** [comment]
I recently started running into this exact issue, also usually my connection is fine to handle the bitrate and sometimes it is not, I would also expect it to reconnect automatically, although technically it is only a drop in connection speed and not a full interruption that I am having I believe. I attached my latest log when this occurred. Strangely, when this happens, I cannot stop the stream or even close obs. I have to open task manager to manually kill the process.
[2021-04-04 22-26-55.txt](https://github.com/obsproject/obs-studio/files/6258645/2021-04-04.22-26-55.txt)
This part is what it logs when the issue occurs I believe. Even if it is unable to send anything for the 30 sec I would hope it would start trying to reconnect.
`03:34:03.799: socket_thread_windows: Received FD_CLOSE, 30075 ms since last send (buffer: 0 / 800768)`
`03:34:03.799: socket_thread_windows: Aborting due to FD_CLOSE, error 0`

Also I found [this reply by a dev](https://obsproject.com/forum/threads/0-kbps-while-the-stream-health-icon-is-on-green.126836/post-472722), so I guess I will disable it for now, although I really like using this feature. In my opinion, having a live stream buffer (adds more delay for the viewer) is worse than one that pixelates (due to lower bitrate) from time to time.

**Comment by theofficialgman** [comment]
@eFFecTM I have also experienced this problem one when using dyncamic bitrate and jim-nvenc for both recording and streaming.

When the the FD_Close error appears the local recording and stream bitrate (separate encodes) drop to 0 and they can not be restarted until an force close of OBS

**Comment by notr1ch** [comment]
Fixed by https://github.com/obsproject/obs-studio/pull/5169

**Comment by eFFecTM** [comment]
@notr1ch Thank you for your work! ❤️‍🔥

**Comment by Techjar** [comment]
This is still happening for me on the latest build. My connection sometimes goes down for like 30 seconds, and occasionally this causes OBS to disconnect and get stuck at 0 kb/s. Stopping the stream won't work, and this condition is unrecoverable, necessitating forcibly killing and restarting OBS.

**Comment by f7ashp0int** [comment]
What is the fix in 2025?
