### ISSUE TITLE
Accessibility Regression In 26.0.0

### ISSUE THREAD

**Issue by OlegVShevkun** [obsproject/obs-studio#3524]
Regression: When using OBS 26.0.0 with any screen reader, control names are no longer spoken as you tab through the Control Doc Bar. This makes it impossible for a blind or severely visually impaired user to start or stop a stream, start or stop recording, change OBS settings, etc.
Please note: this is a regression. While there have been other accessibility issues before, this basic stuff used to work in OBS 25 and earlier.

OS: Windows 10, 64-bit.

Steps to reproduce:
1. Start Narrator. This is the basic screenreader built into Windows, and this will suffice for our quick test.
2. Start OBS.
3. Tab through the controls usint TAB and SHIFT+TAB. As you do this, listen to the feedback you receive.
4. When you reach the controls on the right, such as "Start streaming" or "Start recording", notice that Narrator is silent.
5. For comparison, run OBS 25 or older and repeat the same steps.
Notice that, though some controls are also silent, the Control Bar still works as expected.

**Comment by WizardCM** [comment]
Hmm, on Windows 10 with the buiilt in Narrator, it is definitely reading out the Controls buttons for me.

However, in both 25.0.8 and 26.0.0 I'm seeing that tabbing from Audio Mixer to Scenes/Sources doesn't read out either of those.

**Comment by OlegVShevkun** [comment]
Audio Mixer is another story, and there have been issues all along.
I am going to completely uninstall and reinstall OBS, to see if this fixes the issue with control reading.

**Comment by WizardCM** [comment]
Out of curiosity, what other screen readers are you also seeing this issue with?

**Comment by OlegVShevkun** [comment]
Both JAWS 2021 and NVDA 2020.2.
And... Unfortunately, it was not fixed by uninstalling and reinstalling.
What steps can I take to gather more information to research this?

**Comment by VodBox** [comment]
I have been able to verify this issue using NVDA.

**Comment by OlegVShevkun** [comment]
Thank you Dillon!

**Comment by VodBox** [comment]
For anyone else looking to reproduce the issue, just substitute NVDA in place of Narrator in the original reproduction steps.

**Comment by VodBox** [comment]
So something to note with this issue. If you use Object Navigation in NVDA (as described in the commands quick reference), it'll report all of the correct text when you navigate between buttons. The issue being presented occurs only when using the tab key to select the buttons.

**Comment by OlegVShevkun** [comment]
Another observation here:
With NVDA, if you use Object Navigation and try to move through objects in the Control Doc, these objects seem to be out of order. To confirm, just try to enumerate the objects going forward, and then go backward. You will get inconsistent results.
Also, if you tab through the window, notice that the focus reaches the last control in the dialog, and then returns to the previous control again. 
There seems to be something going on with object ordering here. I wonder if this can also adversely impact accessibility.

**Comment by OlegVShevkun** [comment]
So, basically, here is what happens:
1. You tab into the Controls Doc. The focus lands on Start Streaming.
2. Press TAB once again. The focus goes to Start Recording. So far so good.
3. Press TAB. Notice that the focus jumps to Studio Mode. This is incorrect, because the Virtual Camera control is out of order.
4. Continue tabbing. You will reach "Settings", then "Exit".
5. Tab once again. You will now get back to Virtual Camera.
I wonder if solving this issue of order will also restore accessibility here.

**Comment by Scrxtchy** [comment]
> 
> 
> So, basically, here is what happens:
> 
>     1. You tab into the Controls Doc. The focus lands on Start Streaming.
> 
>     2. Press TAB once again. The focus goes to Start Recording. So far so good.
> 
>     3. Press TAB. Notice that the focus jumps to Studio Mode. This is incorrect, because the Virtual Camera control is out of order.
> 
>     4. Continue tabbing. You will reach "Settings", then "Exit".
> 
>     5. Tab once again. You will now get back to Virtual Camera.
>        I wonder if solving this issue of order will also restore accessibility here.

This is a known issue, a patch has been developed
https://github.com/Scrxtchy/obs-studio/commit/e4c72e76f4580d458561558bcdb72244b99e370f

It was mentioned that this was known before release but it was forgotten about until now

**Comment by OlegVShevkun** [comment]
Sorry folks,
I'd like to test with this patch, but do not have the knowledge or expertese to build from Github. Could someone please make a built patch available? Or at least, a file that I could drop into the current installation? Thanks!

**Comment by Scrxtchy** [comment]
The patch has been merged into master @OlegVShevkun, therefore you should now be able to download a development build with the changes. These builds can be found here; https://github.com/obsproject/obs-studio/actions/runs/284367250
Narrator is now behaving properly for me in comparison to earlier where it crashed frequently. While I was unable to replicate the issues, I do ask for further testing with alternative Screen Readers for a proper accessibility check

https://youtu.be/kzNBp284rw0
In this video, I use <kbd>Tab</kbd> and <kbd>Shift</kbd>+<kbd>Tab</kbd> to navigate through elements in the controls panel, to which the narrator is able to read the content of each button

**Comment by OlegVShevkun** [comment]
Tested with the latest JAWS and NVDA, and this issue appears to be fixed. However, for some reason, on my test system I can no longer see the "Start Virtual Camera" button. But this may be an issue with my specific installation, and it is not related to accessibility. So, for the current issue, it is fixed/verified.
Thank you!

**Comment by Scrxtchy** [comment]
There should be batch files somewhere within the software location (I think it's in data /plugins /virtualcam directory?) that will register and deregister the virtual camera for the development build.

It is something that I am not familiar with though, in development I had just enforced the buttons to be displayed without enabling the feature

**Comment by dodgepong** [comment]
I believe this was fixed in https://github.com/obsproject/obs-studio/pull/3530 yes? Should this be closed now?

**Comment by OlegVShevkun** [comment]
This still does not work in 26.0.2. However, it DID work in a developmental built that was made available last Friday. Would like to re-open this issue.

**Comment by Scrxtchy** [comment]
Cannot Replicate
Windows Narrator: https://youtu.be/nOakPS_p61w
NV Access (from Installer): https://youtu.be/9rwbuKMkPys

**Comment by VodBox** [comment]
@Scrxtchy - The issue occurs with NVDA when using tab in the interface to go over the buttons. Object navigation and cursor reporting are not an issue.

**Comment by Scrxtchy** [comment]
Ahh, thank you, I will look again

**Comment by Scrxtchy** [comment]
Couldn't replicate: https://youtu.be/dVzhS0-jKdE

**Comment by OlegVShevkun** [comment]
Interesting. I am reproducing this with Narrator, JAWS and NVDA, all latest versions.
A couple of notes:
1. In order to re-check, I went ahead and installed the update again. The tab order of controls is now correct, but they still don't speak.
2. I then went ahead and reinstalled last week's dev built mentioned here, and the issue was fixed again.
Are there any specific files that might be worth looking into in order to track this down?

**Comment by Scrxtchy** [comment]
>     2. I then went ahead and reinstalled last week's dev built mentioned here, and the issue was fixed again.
>         Are there any specific files that might be worth looking into in order to track this down?

As far as the file history goes, I am the last person who made changes to it, being the commit that should have fixed it
https://github.com/Scrxtchy/obs-studio/commits/62244002e60072257532d4f7c0649e91b1e3cc88/UI/window-basic-main.cpp

this does make it a very hard puzzle to solve

**Comment by VodBox** [comment]
The one difference with that test build from the main release is the fact that virtual cam doesn't work in the test build. There is also no .bat files (that I can find) that will allow to install and test.

I intend to do some testing on my end.

**Comment by VodBox** [comment]
Important thing I've noted just now: This bug also happens if you have Replay Buffer enabled, except not if enabled when you launch the program. If you enable Replay Buffer, even if you go on to disable it, all the buttons in control stop reporting with the tab key. I don't know what's different with the Replay Buffer button that makes it work on launch, but Virtual Cam doesn't.

**Comment by Scrxtchy** [comment]
Yeah, I get that issue to with the replay buffer. While I understand the replaybuffer controls are a bit weird, it's hard for me to say exactly since I don't know QT that well.
The menu functions correctly when the buttons are already there when we start OBS with the replay buffer, and continues to work when we remove the buttons.
But adding them after the initial UI loading breaks the controls

**Comment by Scrxtchy** [comment]
> The one difference with that test build from the main release is the fact that virtual cam doesn't work in the test build. There is also no .bat files (that I can find) that will allow to install and test.
> 
> I intend to do some testing on my end.

Forgot to mention that this is somewhat intended? The CI doesn't set the argument for building with virtualcamera. If #3564 is merged than this will change. Otherwise [Jim's words here](https://canary.discord.com/channels/348973006581923840/374636084883095554/761125468526870530) are what you want for building with the camera

**Comment by VodBox** [comment]
So forgive me my ignorance here, but I also notice a large number of things in the OBS interface aren't really accessible from tab navigation, particularly things like the visibility and lock buttons for a source. Is tab navigation actually something people use with screen readers over object navigation?

**Comment by OlegVShevkun** [comment]
Object navigation is for more advanced users. To do this, one would have to understand things like object hierarchy. A non-advanced user would just work with hotkeys, or tab through the interface.
Yes, there are plenty of things NOT accessible with tabbing. However, this is exactly the more ADVANCED stuff, and you do not often need to work with these controls. But starting/stopping a stream is part of the basic functionality.

**Comment by Scrxtchy** [comment]
@gabrielschuck which OS and utility do you use?

**Comment by gabrielschuck** [comment]
Hi! I'm using windows 7 and NVDA as a screen reader. I had tried with the latest version, but I'm still not able to read the start / stop recording / transmission buttons. I also have jaws, but I use nvda more.

**Comment by OlegVShevkun** [comment]
This was solved for me by completely removing my OBS Settings folder and restarting for scratch. All of the buttons now read properly with both JAWS and NVDA.

**Comment by OlegVShevkun** [comment]
Folks, I now have exact steps to reproduce the issue with OBS controls not spoken by screen readers. This issue needs to be re-opened.

Summary: OBS controls are not announced by screen readers when the OBS window is maximized, and OBS has been restarted.

Steps:
1. Rename your OBS Settings folder. (You will want to restore it later, so just have backed it up under another name).

2. Start OBS afresh. 

3. Escape out of Autoconfiguration dialog. No need to waste time on this right now.

4. Using a screen reader, tab through OBS buttons. Note that all of the buttons on the right are announced properly.

5. This is the important step: MAXIMIZE the OBS Window.

6. Tab through the buttons. Notice that all of them are still spoken properly. So far so good.

7. Close and then restart OBS. It is now maximized.

8. Tab through the buttons. Notice that the buttons on the right are no longer spoken as you tab.

9. Restore the window to its default size (not maximized).

10. Tab through the buttons. Notice that they are not spoken.

11. Now, close and restart OBS.

12. Tab through the buttons. They are now spoken properly again.

**Comment by VodBox** [comment]
After investigating the issue, while I was not able to determine a root cause, the issue seems to be internal to Qt, and occurred with multiple versions of Qt in testing. When the issue happens, parts of Qt's code that should be called for determining the text to provide to the screen reader just don't run at all, despite checking many different paths the code can/should take.

The newest version of Qt that just released - 5.15.2 - seems to not have the issue (or at least, I can no longer reproduce it after several attempts), however due to incompatibility with at least one major plugin, it is uncertain whether we'll be making that upgrade in the coming OBS update (26.1). We will be updating our Qt version as soon as that incompatibility is sorted out however.

Sorry that things took a while. I'd been busy with finishing my undergraduate study up until this point.

**Comment by gabrielschuck** [comment]
@VodBox Thank you so much for trying to help with this.
Do you then recommend that screen reader users use the latest version with the screen maximized so that everything can be read correctly?
I am still using version 25.0.8.

 I don't know if it is interesting to put it here as well, but there is another problem of accessibility in relation to the option to edit transformation.
It is a window where we can define the resolution of the source and the position, very useful for example if I want a camera next to the other.
From what a friend with low vision commented to me, it is possible to navigate with tab and shift tab through the editing fields, but the screen reader does not speak at all.
I would like to be able to access this screen with accessibility for myself to make these adjustments.
I know I will still depend on a friendly eye, but it will give me a little bit of autonomy especially if I need to add the fonts and do it all over again.
Best regards

**Comment by VodBox** [comment]
So the good news is that we have resolved the issue with the third-party plugin, and so will be using Qt 5.15.2 in the next release, which should fix the issue. I would ask that you test with the release candidate when that comes out to confirm, in case some other factor is at play and affects my ability to reproduce with that version.

I do have a bunch of screen reader fixes ready that I'll try merging before the release, so I can try to fix that other issue you mention as well while I finalize the changes. If I can't get that done in time, it'd be good to make an issue specifically for it so I can then respond with the progress there.

**Comment by VodBox** [comment]
@gabrielschuck - Can you verify this issue is fixed in the new Release Candidate? https://github.com/obsproject/obs-studio/releases/tag/26.1.0-rc1

**Comment by gabrielschuck** [comment]
@VodBox Perfect! The problem has even been solved. The buttons are now being read correctly. Thank you!
I realized that now, when there is only one source or scene in the list, the screen reader is almost always unable to identify. When there is more than one, if he doesn't start reading when I press tab, just a few arrows up or down he detects the list.

About the accessibility on the edit transformation screen, I also noticed that in this version, when giving tab about 6 times, nvda speaks only "group". Then, giving another tab the reader says "up". Another tab, "down". Another tab, "left". And finally, "right". However, it is not possible to edit the values that should appear.
A suggestion: Would it be possible for these values to do as in other obs screens, in which we can navigate with the arrows in a combo box, or in a rotation button?
NVDa usually identifies this element as a "rotation button" in the part where we adjust the duration of the transition.

 Anyway, I can create another issue for this problen if you still feel it is necessary.
Thanks again!

**Comment by gabrielschuck** [comment]
About accessibility in qt ... I remember testing a software called mixxx. It is done in qt and is completely inaccessible with screen readers. But there was a plugin that I put inside the program folder, a folder was created called "accessibility" that made the program very accessible, as if it were really accessible.
I can't say if this plugin still works in newer versions of qt, but it was used by some software developed in qt, such as the old "tapin radio".

**Comment by VodBox** [comment]
The scene item transform dialog has now been fixed by [this commit.](https://github.com/obsproject/obs-studio/commit/58b2da73b31a8b69181663c5384290c8cb7c288a)

Unfortunately there is a remaining issue with NVDA where position, size, rotation and bounding box sizes report their value as 50 when you first select the input, however it reports correctly when you change the value. Narrator reports the value just fine, and I don't have a copy of JAWS on hand to test with that, but I was unable to find anything in OBS or in Qt that would explain why 50 would appear. I'm suspecting NVDA has a bug when spinners contain non-integer ranges and values.

Since that issue is only affecting one screen reader application, and it's either an issue with NVDA or Qt, I'm going to consider that not an issue on our end, but one that I'll be still trying to remedy once I have more understanding of the problem.

For now, I'm closing this issue since all the issues mentioned here have now been fixed.
