### ISSUE TITLE
Gnome Tweaks Scaling Factor garbles OBS interface in 26.1

### ISSUE THREAD

**Issue by InFerYes** [obsproject/obs-studio#4031]
## Platform

Operating system and version: Arch Linux (5.10.4-arch2-1)
OBS Studio version: 26.1.0-2

## Expected Behavior

OBS interface should look normal when font scaling is applied in Gnome Tweaks
![https://i.imgur.com/nti37zC.png](https://i.imgur.com/nti37zC.png)

## Current Behavior

OBS interface is completely garbled when font scaling is applied in Gnome Tweaks
![https://i.imgur.com/p8kpuK5.png](https://i.imgur.com/p8kpuK5.png)

When going from windowed to maximized makes it worse: ![https://i.imgur.com/7v9QPBx.png](https://i.imgur.com/7v9QPBx.png)

## Steps to Reproduce

1. Open Gnome Tweaks and go to the Fonts tab
2. Set the Scaling Factor to 0.90 ![https://i.imgur.com/oVBaSuu.png](https://i.imgur.com/oVBaSuu.png)
3. Open OBS
4. Interface unusable
5. In Tweaks, set Scaling Factor to 1 ![https://i.imgur.com/lH3TGrS.png](https://i.imgur.com/lH3TGrS.png)
6. OBS looks normal

## Additional information

This issue was not present in version 25.x, as I always had the Scaling Factor set to 0.90. KeepassXC had a similar problem earlier this year: https://github.com/keepassxreboot/keepassxc/issues/5029

**Comment by LGCW** [comment]
Same issue on Debian testing. 

![Screenshot_2021-01-07_08-11-21](https://user-images.githubusercontent.com/3475462/103896523-1a4b0880-50c0-11eb-8e38-305429528d33.png)

`export QT_SCALE_FACTOR=1.1` fixes it on this end.

**Comment by WizardCM** [comment]
I could have sworn we had a ticket for this already. Hmm.

This can be considered a known issue, basically we added improved scaling support (as did our UI library, Qt) which supports fractional scaling.

Unfortunately, it seems to misbehave on Linux. The plan is to verify whether the fractional scaling support causes any issues on macOS, and then submit a PR that disables it on (at least) Linux.

**Comment by InFerYes** [comment]
```
QMake version 3.1
Using Qt version 5.15.2 in /usr/lib
```

**Comment by LGCW** [comment]
5.15.2

**Comment by FireStarW** [comment]
Just to give more data, I run into this issue on Ubuntu 20.10 with lxqt, which does not even really have HiDPI support.

![image](https://user-images.githubusercontent.com/11762725/103959250-2f09b980-511d-11eb-8be6-23495027b791.png)

If I run
`~$ echo $QT_SCALE_FACTOR`
It returns nothing, so I don't believe any hi DPI settings that lxqt could use are on.

My QT version is 5.14.2 

The interface renders just fine when launching OBS in the Cinnamon DE, on the same computer, as opposed to lxqt.

**Comment by kkartaltepe** [comment]
Font scaling less than 1 doesnt appear to work in any Qt programs, it seems Qt does not support them nor make it easy to try and avoid this bug. I recommend you force a compatible dpi/rounding value for qt applications. Choose your favorite from some of the available flavors.
QT_SCALE_FACTOR_ROUNDING_POLICY=Round
QT_FONT_DPI=96
QT_SCALE_FACTOR=1

For others, is your scale factor greater than 1? I cannot replicate the issue on qt 5.12 with fractional scaling greater than 1 (1.1 -> 2.0 all render fine). Are you using other more exotic attempts at hidpi? Please provide exactly how you are configuring hidpi support.

**Comment by InFerYes** [comment]
I have set the scaling factor to 1 until this is resolved, but having users define env vars is not a permanent solution. People who don't have these set will still have the issue and might not know about (these) env vars.

**Comment by kkartaltepe** [comment]
of course, the permanent solution is to get Qt to fix their bug for users with scaling factors less than 1.

**Comment by alkaris2** [comment]
This is still an issue, and I'm on Cinnamon on Manjaro Linux. I use text scaling of 0.8 as opposed to text scaling of 1.0 on HIDPI monitor.

Here's few screenshots for comparison.

![flameshot_2021-01-17__02_49_57_PM](https://user-images.githubusercontent.com/73155407/104830938-a71d6f80-58d3-11eb-93f7-75cc94d9d43e.png)
![flameshot_2021-01-17__02_50_17_PM](https://user-images.githubusercontent.com/73155407/104830939-a8e73300-58d3-11eb-9cb3-674349c4d6bf.png)

Could you perhaps include the provided QT_SCALE_FACTOR and QT_FONT_DPI in the build so then they scale properly based on whatever the scaling is set on the system instead of hardcoding it.

Previous build didn't seem to have this issue, but in the new build it has this issue, so whatever you had before wasn't an issue.

**Comment by WizardCM** [comment]
The fix I committed doesn't use any hardcoding, it just removes fractional scaling seeing as it misbehaves on Linux. We'll revisit in future for sure.

**Comment by Marto32** [comment]
I'm still experiencing this issue ([see my question on the OBS forums](https://obsproject.com/forum/threads/weird-ui-artifact-glitch-after-installing-obs-on-linux-mint.139216/)), is there a permanent fix for this?

I'm using OBS (v26.1.1) on Mint (v20.1 - Cinnamon) on a Dell 4k monitor running at double (Hi DPI) user interface scale. I can run `export QT_SCALE_FACTOR=1.2` and launch OBS from the command line for a quick/incomplete fix but I have no such luck launching the app from the desktop icon or task bar.

**Comment by Aisyk** [comment]
Hi,
Same issue here with that program, RPCS3 : https://github.com/RPCS3/rpcs3/issues/8095

Solution is to launch program with : `QT_ENABLE_HIGHDPI_SCALING=0`

Because, `QT_AUTO_SCREEN_SCALE_FACTOR` was replaced with `QT_ENABLE_HIGHDPI_SCALING` in Qt 5.14.

**Comment by Aisyk** [comment]
> I'm still experiencing this issue ([see my question on the OBS forums](https://obsproject.com/forum/threads/weird-ui-artifact-glitch-after-installing-obs-on-linux-mint.139216/)), is there a permanent fix for this?
> 
> I'm using OBS (v26.1.1) on Mint (v20.1 - Cinnamon) on a Dell 4k monitor running at double (Hi DPI) user interface scale. I can run `export QT_SCALE_FACTOR=1.2` and launch OBS from the command line for a quick/incomplete fix but I have no such luck launching the app from the desktop icon or task bar.

You could edit your obs.desktop to fit with the correct launching command.

**Comment by Metagit** [comment]
I am also still experiencing this issue. If I use QT_SCALE_FACTOR=.5 obs it works, but everytahing is super tiny...

**Comment by Zeioth** [comment]
In sway, running obs with QT_SCALE_FACTOR=1 works fine, but any other scaling factor make obs controls unclicable.
