### ISSUE TITLE
OBS-Studio doesn't accept nginx rtmp unless fully restarted

### ISSUE THREAD

**Issue by IKHNetworks** [obsproject/obs-studio#4220]
The latest update of OBS-Studio has recently introduced a big bug that seems to be related to the use of nginx rtmp servers. This issue is often related to using a custom built nginx rtmp server - with the template from the official obs-studio forums that still appears to cause failure to connect or indicates some sort of error message relating to the server - however restarting the nginx service appears to be the fix. However this also impacts other websites where I also have nginx setup. 
## Platform

Operating system and version: Windows 10 - May 2020 Update
OBS Studio version: 26.1.1  

## Expected Behavior

When a disconnect happens - it should not require a full blown server restart to get back online via the stream option. 
## Current Behavior

The latest update of OBS-Studio has recently introduced a big bug that seems to be related to the use of nginx rtmp servers. This issue is often related to using a custom built nginx rtmp server - with the template from the official obs-studio forums that still appears to cause failure to connect or indicates some sort of error message relating to the server - however restarting the nginx service appears to be the fix. However this also impacts other websites where I also have nginx setup. 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by WizardCM** [comment]
Please fill in the template (especially the steps) and provide more technical details about the issue you're running into.

Additionally, is this fixed by #4147? You can grab the latest nightly at the bottom [of this page](https://github.com/obsproject/obs-studio/actions/runs/551055552).

**Comment by henke37** [comment]
One thing I wonder is if this issue is on the client or on the server. If a different client connects to the server, does the issue persist on the server? The same for the same client connecting to a different server.

**Comment by IKHNetworks** [comment]
The issue was still the same on a different server. I tried using restream.io and the same thing occurred - not just on my private rtmp server.

**Comment by IKHNetworks** [comment]
The issue doesn't seem to be happening on the nightly build though.

**Comment by Fenrirthviti** [comment]
Duplicate of https://github.com/obsproject/obs-studio/issues/2865
