### ISSUE TITLE
DLog logging turned on for mac-virtualcam, dirties command line tools

### ISSUE THREAD

**Issue by rharder** [obsproject/obs-studio#4285]
## Platform

Operating system and version: Mac OS (Mojave and Big Sur)
OBS Studio version: 26.1.2
OBS Log file:

## Expected Behavior

Enumerating AVCaptureDevice devices should not print mac-virtualcam(DAL) log messages to console

## Current Behavior

I have a command line tool (github.com/rharder/imagesnap), and when it enumerates cameras with [AVCaptureDevice devicesWithMediaType:AVMediaTypeVideo], 14 log lines from mac-virtualcam(DAL) are printed out to the console, dirtying up the user interface of the tool.  It would be great if those log messages could be turned off.

## Steps to Reproduce

1. In a working Objective-C Mac environment, the following device enumeration causes mac-virtualcam(DAL) log messages to be printed:  [AVCaptureDevice devicesWithMediaType:AVMediaTypeVideo]

## Additional information

These are the log messages that are printed:

2021-02-27 21:15:06.008 imagesnap[50490:1522273] mac-virtualcam(DAL): PlugInMain version=1.3.0
2021-02-27 21:15:06.008 imagesnap[50490:1522273] mac-virtualcam(DAL): HardwarePlugIn_QueryInterface 
2021-02-27 21:15:06.008 imagesnap[50490:1522273] mac-virtualcam(DAL): HardwarePlugIn_Release sRefCount now = 0
2021-02-27 21:15:06.008 imagesnap[50490:1522273] mac-virtualcam(DAL): HardwarePlugIn_InitializeWithObjectID self=0x10ac65478
2021-02-27 21:15:06.008 imagesnap[50490:1522273] mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData OBSDALDevice(33) kCMIOObjectPropertyListenerAdded self=0x10ac65478 data(int)=1684629094
2021-02-27 21:15:06.008 imagesnap[50490:1522273] mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData OBSDALDevice(33) kCMIOObjectPropertyListenerAdded self=0x10ac65478 data(int)=1869180523
2021-02-27 21:15:06.008 imagesnap[50490:1522273] mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData OBSDALDevice(33) kCMIOObjectPropertyListenerAdded self=0x10ac65478 data(int)=1885762592
2021-02-27 21:15:06.112 imagesnap[50490:1522273] mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData OBSDALDevice(33) kCMIOObjectPropertyListenerAdded self=0x10ac65478 data(int)=1818850926
2021-02-27 21:15:06.112 imagesnap[50490:1522273] mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData OBSDALDevice(33) kCMIOObjectPropertyListenerAdded self=0x10ac65478 data(int)=1869180523
2021-02-27 21:15:06.112 imagesnap[50490:1522273] mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData OBSDALDevice(33) kCMIOObjectPropertyListenerAdded self=0x10ac65478 data(int)=1937009955
2021-02-27 21:15:06.112 imagesnap[50490:1522273] mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData OBSDALDevice(33) kCMIOObjectPropertyListenerAdded self=0x10ac65478 data(int)=1886156132
2021-02-27 21:15:06.112 imagesnap[50490:1522273] mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData OBSDALDevice(33) kCMIOObjectPropertyListenerAdded self=0x10ac65478 data(int)=1935833461
2021-02-27 21:15:06.112 imagesnap[50490:1522273] mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData OBSDALStream(34) kCMIOObjectPropertyListenerAdded self=0x10ac65478 data(int)=1885762592

**Comment by jp9000** [comment]
Yea, generally even with LOG_DEBUG it's ideal to avoid too much log spam if it can be avoided or reduced somehow or another. But if it's a one time thing it's not *too* big of a deal. It's really bad if it ends up once per frame or something, but this is only on enumeration so it's probably less pressing.

**Comment by rharder** [comment]
OK thanks, I understand it's low priority.

**Comment by gxalpha** [comment]
This should be fixed in 5708e64d113aa77234e97c75e5a00e9ba1c78a9d, right?

**Comment by RytoEX** [comment]
> 
> 
> This should be fixed in [5708e64](https://github.com/obsproject/obs-studio/commit/5708e64d113aa77234e97c75e5a00e9ba1c78a9d), right?

@gxalpha Upon inspecting the commit in question and code that calls the logging function, that does appear that it should resolve this Issue, so I'm going to close this.  MacOS users can verify this with a recent CI build or with 27.0.0-rc3 whenever we release that.  If this Issue is not fixed, please feel free to comment, and we can reopen this Issue.

**Comment by umutbalkan** [comment]
Same issue persist even if install OBS 27. Also seems like uninstalling OBS does not get rid of mac-virtualcam (DAL) plugin.
I'm running macos Catalina.

So when I list the connected capture devices using
`ffmpeg -f avfoundation -list_devices true -i ""`


Here is the log:

ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with Apple clang version 12.0.0 (clang-1200.0.32.27)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.3.1_4 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
2022-09-29 08:18:20.925 ffmpeg[743:12289] mac-virtualcam(DAL): PlugInMain version=1.3.0
2022-09-29 08:18:20.925 ffmpeg[743:12289] mac-virtualcam(DAL): HardwarePlugIn_QueryInterface 
2022-09-29 08:18:20.925 ffmpeg[743:12289] mac-virtualcam(DAL): HardwarePlugIn_Release sRefCount now = 0
2022-09-29 08:18:20.925 ffmpeg[743:12289] mac-virtualcam(DAL): HardwarePlugIn_InitializeWithObjectID self=0x10f8e0478
2022-09-29 08:18:20.926 ffmpeg[743:12289] mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData OBSDALDevice(33) kCMIOObjectPropertyListenerAdded self=0x10f8e0478 data(int)=1684629094
2022-09-29 08:18:20.926 ffmpeg[743:12289] mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData OBSDALDevice(33) kCMIOObjectPropertyListenerAdded self=0x10f8e0478 data(int)=1869180523
2022-09-29 08:18:20.926 ffmpeg[743:12289] mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData OBSDALDevice(33) kCMIOObjectPropertyListenerAdded self=0x10f8e0478 data(int)=1885762592
2022-09-29 08:18:21.095 ffmpeg[743:12289] mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData OBSDALDevice(33) kCMIOObjectPropertyListenerAdded self=0x10f8e0478 data(int)=1818850926
2022-09-29 08:18:21.095 ffmpeg[743:12289] mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData OBSDALDevice(33) kCMIOObjectPropertyListenerAdded self=0x10f8e0478 data(int)=1869180523
2022-09-29 08:18:21.095 ffmpeg[743:12289] mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData OBSDALDevice(33) kCMIOObjectPropertyListenerAdded self=0x10f8e0478 data(int)=1937009955
2022-09-29 08:18:21.095 ffmpeg[743:12289] mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData OBSDALDevice(33) kCMIOObjectPropertyListenerAdded self=0x10f8e0478 data(int)=1886156132
2022-09-29 08:18:21.095 ffmpeg[743:12289] mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData OBSDALDevice(33) kCMIOObjectPropertyListenerAdded self=0x10f8e0478 data(int)=1935833461
2022-09-29 08:18:21.095 ffmpeg[743:12289] mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData OBSDALStream(34) kCMIOObjectPropertyListenerAdded self=0x10f8e0478 data(int)=1885762592
[AVFoundation indev @ 0x7f95e440d1c0] AVFoundation video devices:
**[AVFoundation indev @ 0x7f95e440d1c0] [0] OBS Virtual Camera**
[AVFoundation indev @ 0x7f95e440d1c0] [1] FaceTime HD Camera (Built-in)
[AVFoundation indev @ 0x7f95e440d1c0] [2] Capture screen 0
[AVFoundation indev @ 0x7f95e440d1c0] AVFoundation audio devices:
[AVFoundation indev @ 0x7f95e440d1c0] [0] BlackHole 2ch
[AVFoundation indev @ 0x7f95e440d1c0] [1] Built-in Microphone
[AVFoundation indev @ 0x7f95e440d1c0] [2] ZoomAudioDevice

OBS Virtual Camera still exist after I removed  and also after I reinstalled OBS 28.0.2. @PatTheMav
