### ISSUE TITLE
"Check for updates automatically?" dialog stuck open

### ISSUE THREAD

**Issue by KM4YRI** [obsproject/obs-studio#4904]
### Operating System Info

macOS 10.15

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/EvPXoxT7029JbLQE

### Expected Behavior

The "Check for updates automatically?" dialog should close after I select either "Don't check" or "Check automatically". 

### Current Behavior

No matter how many times I click either button (don't check, or check automatically), the dialog persists.  It does not close.  If OBS is closed and re-opened, the dialog reappears and persists.

### Steps to Reproduce

This was the first time that I've ever installed OBS Studio on this machine.  I simply ran the installer, and opened the application.  There were no specific configurations or unique characteristics that led to this behavior.

### Anything else we should know?

I searched through open and closed issues before posting this.  I didn't find any similar issues.  Apologies if this is a known behavior.

**Comment by dossy** [comment]
The string "Check for updates automatically?" is found in "SUUpdatePermissionPrompt.nib" ... perhaps there's an issue with OBS's integration of Sparkle.

@KM4YRI, once you've launched OBS.app, can you click on the "Settings" button and under General, tell me what your "Automatically check for updates on startup" setting is, whether it's checked or not?

If you have it checked, can you try unchecking it and then exiting OBS.app and relaunching it?  Does that prevent the "Check for updates automatically?" dialog from opening when you start OBS?

**Comment by KM4YRI** [comment]
@dossy, the setting was checked in the preferences page.  When I disable it, and relaunch, yes, the dialog goes away.  It is an effective workaround.  It's just not an obvious one, and I could see a lot of newcomers getting confused at it, as is what happened to me.

I got pretty frustrated at the Mac build, because it does not appear to support hardware video encoding, even though my Mac has the ability to encode in hardware.  So I switched my OBS setup to a Windows PC.  It'd be great if these things ever get resolved in the Mac version.  I'll be donating / contributing to the OBS project in the future, as my budget allows.  I'd very much like that to be spent on Mac / OSX development, if possible.  OBS is a fantastic application and it deserves to be just as great on Mac.  Thanks to all the OBS developers for their hard work.

**Comment by PatTheMav** [comment]
> does not appear to support hardware video encoding

Hardware encoding is supported on all recent Macs via VideoToolbox. Could you pls specify what you mean by "does not appear to" - do you have a specific use case that you could not set up as intended?

As for the update checks, that is all handled by Sparkle and I wasn't able to reproduce/force the reported behaviour on 4 different Macs, I don't have Macs with anything older than Big Sur though, so I cannot rule out a 10.15-specific issue, but also haven't heard of this being a widespread issue so far.

Sparkle stores its metadata in `~/Library/Preferences/com.obsproject.obs-studio.plist` (look for any key starting with `SU`), in my case the values look something like this:

```
    <key>SUEnableAutomaticChecks</key>
    <true/>
    <key>SUHasLaunchedBefore</key>
    <true/>
    <key>SULastCheckTime</key>
    <date>2021-06-25T14:03:16Z</date>
    <key>SUSendProfileInfo</key>
    <false/>
    <key>SUSkippedVersion</key>
    <string>26.1.0</string>
    <key>SUUpdateGroupIdentifier</key>
    <integer>INT_NUMBER</integer>
    <key>SUUpdateRelaunchingMarker</key>
    <false/>
```

**Comment by RytoEX** [comment]
> The "Check for updates automatically?" dialog should close after I select either "Don't check" or "Check automatically".

I got this dialog to spawn once and clicked "Check Automatically" and the dialog closed immediately.  I'll try to explore this more some other time.

> OS Version: Version 10.15.7 (Build 19H114)

Does this issue occur on macOS 10.15.7 with the latest security and supplemental updates?


> I got pretty frustrated at the Mac build, because it does not appear to support hardware video encoding, even though my Mac has the ability to encode in hardware.

OBS asks macOS what VideoToolbox encoders are supported by the system and loads the ones macOS tells us the system supports.  OBS only shows these encoders in Advanced Output Mode because they are not recommend for streaming because, if I recall correctly, they do not handle CBR correctly, which nearly all major streaming platforms recommend or require.

However, this is diverging from the issue of whether or not the Sparkle updater is working correctly, and I'd rather not complicate this issue with that discussion.  There is a known issue presently with eGPUs (#4942).  You're welcome to connect with us on our forums or Discord to determine if there is some other actual bug with Apple VT encoders.

**Comment by PurpleSorcerer** [comment]
I'm seeing this exact behavior in OBS 27.0.1 on a Mad Mini (M1, 2020) running MacOS 11.5.2 with all updates. Turning off the preference clears the dialog.

**Comment by DolphinDoug** [comment]
Another Mac user here with the same problem running Big Sur on an Early 2015 MBP with OBS 27.0.1. Soon to update to an M1 MBA, worried this won't go away. I can turn it off through preferences (Thanks!). I'm a complete noob, so I can't provide any help, but I completely agree with the original post that streaming on a Mac seems inappropriately frustrating. Thanks.

**Comment by samj** [comment]
Same issue with latest OBS (27.1.0) on latest macOS Monterey beta (21A5534d). Did have a fish around in the code for something obvious and found it's likely related to integration with Sparkle, which I know nothing about:

https://github.com/obsproject/obs-studio/blob/422a20637180d55019f7f636039529981f33f50b/UI/window-basic-main.cpp#L3603

This takes us here:
https://github.com/obsproject/obs-studio/blob/dde4d57d726ed6d9e244ffbac093d8ef54e29f44/UI/sparkle-updater.mm#L140

The checkForUpdates function is Sparkle (note warnings about race conditions, and that this is v1 docs, not v2):
https://sparkle-project.org/documentation/customization/

```
// This IBAction is meant for a main menu item. Hook up any menu item to this action,
// and Sparkle will check for updates and report back its findings through UI.
- (IBAction)checkForUpdates:sender;
```

Seems to me that this should not be called at this time as it's meant to be called from a menu item, and in any case it should be told who the sender is (currently nil) so it can report back? https://github.com/sparkle-project/Sparkle/blob/1dea9705127932db033b4ba48d77789d1ac64823/Sparkle/SPUUpdater.h#L89

Some other threads to pull on from search results:

update checkbox:
https://github.com/obsproject/obs-studio/blob/422a20637180d55019f7f636039529981f33f50b/UI/forms/OBSBasicSettings.ui#L232

default to on: 
https://github.com/obsproject/obs-studio/blob/c459e8954c330eadf075fd825185225e780f8d5f/UI/obs-app.cpp#L419

actual updates: TimedCheckForUpdates()
https://github.com/obsproject/obs-studio/blob/422a20637180d55019f7f636039529981f33f50b/UI/window-basic-main.cpp#L3611
https://github.com/obsproject/obs-studio/blob/422a20637180d55019f7f636039529981f33f50b/UI/window-basic-main.cpp#L3599

if not windows/apple, delete ui->enableAutoUpdates
https://github.com/obsproject/obs-studio/blob/afd58a78e5fe88149d39d5b0c11c195797d22c29/UI/window-basic-settings.cpp#L581

check config, setChecked(enableAutoUpdates)
https://github.com/obsproject/obs-studio/blob/afd58a78e5fe88149d39d5b0c11c195797d22c29/UI/window-basic-settings.cpp#L1222

SaveGeneralSettings -> EnableAutoUpdates
https://github.com/obsproject/obs-studio/blob/afd58a78e5fe88149d39d5b0c11c195797d22c29/UI/window-basic-settings.cpp#L2989

<img width="698" alt="Screen Shot 2021-10-01 at 8 56 21 AM" src="https://user-images.githubusercontent.com/726034/135549891-9cd39f96-4719-4a3c-b6d9-3fb25d89db4d.png">
<img width="952" alt="Screen Shot 2021-10-01 at 8 57 58 AM" src="https://user-images.githubusercontent.com/726034/135549893-0475855f-9a7a-4a6a-891a-a94cbe4fcc1e.png">
<img width="550" alt="Screen Shot 2021-10-01 at 8 56 12 AM" src="https://user-images.githubusercontent.com/726034/135549895-517c3450-e044-48af-8c6c-2ffbfdfc6ef7.png">

**Comment by WizardCM** [comment]
Following up from @samj's research:

[Source](https://sparkle-project.org/documentation/customization/)

It does confirm that when we do an automatic check for updates, we should actually be using `checkForUpdatesInBackground()`. Though it doesn't say whether it triggers the "Check for updates automatically" dialog from Sparkle. Interestingly, the docs for the delegate do say:

```
// Use this to override the default behavior for Sparkle prompting the
// user about automatic update checks. You could use this to make Sparkle
// prompt for permission on the first launch instead of the second.
- (BOOL)updaterShouldPromptForPermissionToCheckForUpdates:(SUUpdater *)bundle;
```

Maybe Sparkle will show the dialog regardless purely because it's initialised, and we're causing it to lock up by checking for updates while it's trying to check for updates?

**Comment by samj** [comment]
I made the mistake of trying to debug someone else's code before my first coffee so taking another look. Problematic call looks to be during initialisation:

https://github.com/obsproject/obs-studio/blob/422a20637180d55019f7f636039529981f33f50b/UI/window-basic-main.cpp#L1894

We're calling TimedCheckForUpdates which may or may not be what we want (seems someone just wanted to tickle it manually to get it to throw up that dialog?):
https://github.com/obsproject/obs-studio/blob/422a20637180d55019f7f636039529981f33f50b/UI/window-basic-main.cpp#L3606

This then calls init_sparkle_updater which instantiates an SUUpdater and assigns an SUUpdaterDelegate (OBSSparkleUpdateDelegate), in which case the windows shenanigans is Sparkle realising it hasn't asked permission? 
https://github.com/obsproject/obs-studio/blob/422a20637180d55019f7f636039529981f33f50b/UI/window-basic-main.cpp#L3615

We could have a debate here about whether we should autoupdate for security/stats/etc. but being OSS and having offline users asking for permissions seems correct, and the problem is not in that decision but rather handling windows relating to it.

I note that SUUpdater is the old way: https://sparkle-project.org/documentation/#basic-setup

"If you are using Sparkle 2, SUUpdater is a deprecated stub. While it is still functional for transitional purposes, new applications will want to use SPUStandardUpdaterController in the above steps instead."

They also have some instructions on setting it up programmatically rather than just dropping in the framework, which we (i.e. someone who knows this stuff better than me) may want to revisit: https://sparkle-project.org/documentation/programmatic-setup/

I spotted updaterMayCheckForUpdates (to suppress Sparkle during e.g. setup wizards) and updaterWillShowModalAlert (to "give the host the opportunity to hide attached windows that may get in the way") and it occurs to me that we are opening the main window around the same time so it could be an ordering/race issue.

Sorry I can't be more useful here, but hopefully this is pointing in the direction of a solution.

**Comment by PatTheMav** [comment]
> I note that SUUpdater is the old way: https://sparkle-project.org/documentation/#basic-setup
> 
> "If you are using Sparkle 2, SUUpdater is a deprecated stub. While it is still functional for transitional purposes, new applications will want to use SPUStandardUpdaterController in the above steps instead."

We do not use Sparkle 2 yet, as it's still in beta - doesn't apply.

> They also have some instructions on setting it up programmatically rather than just dropping in the framework, which we (i.e. someone who knows this stuff better than me) may want to revisit: https://sparkle-project.org/documentation/programmatic-setup/

You're mixing up a few things here - you always need to "drop in"/link the framework. Besides, OBS uses Qt as our UI toolkit and as such doesn't use Storyboards in Xcode (and thus there is no MainMenu.xib), so we cannot use the common way of just wiring up a menu item associated with a Sparkle updater object _or_ the programmatic way of hooking up an `IBOutlet` (because you have to connect an `IBOutlet` with the associated menu bar item in a Storyboard).

Both things require using `AppKit` which OBS does not. The documentation you linked explicitly mentions to use `-[SUUpdater checkForUpdates:]` to check for updates using "another UI toolkit" (which we do). There is no harm in invoking a function flagged as an `IBOutlet` as-is. `sender` would just be a reference to the button/object that triggered the action, which isn't even used by Sparkle: `- (IBAction)checkForUpdates:(id)__unused sender`.

> The checkForUpdates function is Sparkle (note warnings about race conditions, and that this is v1 docs, not v2):
https://sparkle-project.org/documentation/customization/

The warning about race conditions only applies for functions setting user preferences (such as enabling/disabling automatic checks), which Sparkle handles automatically after the initial launch of an application. We don't interfere with Sparkle in this case and let it do its thing.

> It does confirm that when we do an automatic check for updates, we should actually be using `checkForUpdatesInBackground()`

While both functions call `checkForUpdatesWithDriver` internally anyway (`checkForUpdatesInBackground` allows fully automatic downloading of new updates, while `checkForUpdates` allows the user to resume a previously aborted update) the former should be used by code to trigger an update out-of-schedule, while the latter should be used by a UI event (e.g. the "Check for Updates" menu bar item).

---

Long story short - this seems to be another case of cross platform code not being aware of things being different on macOS:

Sparkle will ask the user for consent to automatic updates on the second (iirc) launch of the app and will periodically check. If an update is found, it'll either show the download prompt or download it automatically. If the user wants to disable this check, we'd just need to set the `automaticallyChecksForUpdates` on the `SUUpdater` object (with the chance of race conditions - see above) and that's it.

Instead OBS on macOS has Sparkle _and_ OBS itself regularly check for updates, interfering with each other. I don't see this interference as impacting functionality, it's just code smell.

As for this issue, it's related to the `SUUpdatePermissionPrompt` which just uses `[NSApp runModalForWindow]` under the hood, so I can _imagine_ some issue with Qt there or maybe another modal window blocking input, but as I haven't been able to replicate this, I wasn't able to dig into this.

**Comment by samj** [comment]
> > I note that SUUpdater is the old way: https://sparkle-project.org/documentation/#basic-setup
> > "If you are using Sparkle 2, SUUpdater is a deprecated stub. While it is still functional for transitional purposes, new applications will want to use SPUStandardUpdaterController in the above steps instead."
> 
> We do not use Sparkle 2 yet, as it's still in beta - doesn't apply.

Right you are... I wonder if it's fixed in v2?

> > They also have some instructions on setting it up programmatically rather than just dropping in the framework, which we (i.e. someone who knows this stuff better than me) may want to revisit: https://sparkle-project.org/documentation/programmatic-setup/
> 
> You're mixing up a few things here - you always need to "drop in"/link the framework. Besides, OBS uses Qt as our UI toolkit and as such doesn't use Storyboards in Xcode (and thus there is no MainMenu.xib), so we cannot use the common way of just wiring up a menu item associated with a Sparkle updater object _or_ the programmatic way of hooking up an `IBOutlet` (because you have to connect an `IBOutlet` with the associated menu bar item in a Storyboard).
> 
> Both things require using `AppKit` which OBS does not. The documentation you linked explicitly mentions to use `-[SUUpdater checkForUpdates:]` to check for updates using "another UI toolkit" (which we do). There is no harm in invoking a function flagged as an `IBOutlet` as-is. `sender` would just be a reference to the button/object that triggered the action, which isn't even used by Sparkle: `- (IBAction)checkForUpdates:(id)__unused sender`.

Cool so you understand this far better than I do, and this isn't it... happy days. All this is also why I'm not a macOS coder :)

> > The checkForUpdates function is Sparkle (note warnings about race conditions, and that this is v1 docs, not v2):
> > https://sparkle-project.org/documentation/customization/
> 
> The warning about race conditions only applies for functions setting user preferences (such as enabling/disabling automatic checks), which Sparkle handles automatically after the initial launch of an application. We don't interfere with Sparkle in this case and let it do its thing.

There is some interaction with the preference checkbox though, the the problem (and updates!) are gone when you turn this off.

> > It does confirm that when we do an automatic check for updates, we should actually be using `checkForUpdatesInBackground()`
> 
> While both functions call `checkForUpdatesWithDriver` internally anyway (`checkForUpdatesInBackground` allows fully automatic downloading of new updates, while `checkForUpdates` allows the user to resume a previously aborted update) the former should be used by code to trigger an update out-of-schedule, while the latter should be used by a UI event (e.g. the "Check for Updates" menu bar item).
> 
> Long story short - this seems to be another case of cross platform code not being aware of things being different on macOS:
> 
> Sparkle will ask the user for consent to automatic updates on the second (iirc) launch of the app and will periodically check. If an update is found, it'll either show the download prompt or download it automatically. If the user wants to disable this check, we'd just need to set the `automaticallyChecksForUpdates` on the `SUUpdater` object (with the chance of race conditions - see above) and that's it.
> 
> Instead OBS on macOS has Sparkle _and_ OBS itself regularly check for updates, interfering with each other. I don't see this interference as impacting functionality, it's just code smell.

Yes, seems a bit silly but there's flags for functionality like this so I expect using one or the other isn't a big change... I presumed it to be the case already! Doesn't seem to be the cause of this problem in any case.

> As for this issue, it's related to the `SUUpdatePermissionPrompt` which just uses `[NSApp runModalForWindow]` under the hood, so I can _imagine_ some issue with Qt there or maybe another modal window blocking input, but as I haven't been able to replicate this, I wasn't able to dig into this.

If the updater ran before the main window opened, the latter would likely steal the focus (so to speak) from the former, no? Refocusing on the offending dialog doesn't fix it so it may be "blocking input" indeed.

**Comment by chipsenkbeil** [comment]
I'm seeing the same issue with OBS Studio 27.1.3 (64 bit) when running on a Mac Mini (M1) 2020 via Big Sur 11.6.1.

![image](https://user-images.githubusercontent.com/2481802/148666164-3a53e7dd-986d-40b9-b24a-3bc28396f652.png)

![OBS_Automatically_Check](https://user-images.githubusercontent.com/2481802/148666192-9346a2eb-4c72-4bc0-beeb-c084ed70d14c.gif)

**Comment by bermudalocket** [comment]
This is still an issue in OBS 27.2.4 on macOS Monterey 12.3.1 (Intel).

Happy one year bug-iversary!

**Comment by Nitrodist** [comment]
This affects me, M1 Mac running OBS - 


<img width="1080" alt="Screenshot 2022-05-21 at 1 34 31 PM" src="https://user-images.githubusercontent.com/385448/169664813-0b051735-5457-488e-bb91-7a6dbed96c2c.png">

<img width="952" alt="Screenshot 2022-05-21 at 1 34 47 PM" src="https://user-images.githubusercontent.com/385448/169664825-c8b9a839-0320-450b-9ed6-3e50c3ee8749.png">

**Comment by Nitrodist** [comment]
OK, so I woke my mac up and clicked the 'Don't notify me' button and it went away.

Here is the log from that run of OBS: https://gist.github.com/Nitrodist/f8547517614c6c24154634b6fbb87453

**Comment by zorgiepoo** [comment]
> Instead OBS on macOS has Sparkle and OBS itself regularly check for updates, interfering with each other. I don't see this interference as impacting functionality, it's just code smell.

Looking at the code, OBS does not appear to regularly check for updates itself on macOS so I don't think there's an interference. So this looks fine currently (see `OBSBasic::TimedCheckForUpdates()`).

OBS may want to consider always initializing the updater (instead of only when OBS enables auto-updates) and set `automaticallyChecksForUpdates` appropriately however because it provides a menu item for the user to check for updates manually, which doesn't work when the updater isn't initialized.

> As for this issue, it's related to the SUUpdatePermissionPrompt which just uses [NSApp runModalForWindow] under the hood, so I can imagine some issue with Qt there or maybe another modal window blocking input, but as I haven't been able to replicate this, I wasn't able to dig into this.

I can't reproduce this issue on a quick attempt, but Sparkle 2 doesn't run this window as modal anymore. Although `OBSSparkleUpdateDelegate` needs some work to migrate; for example, returning a delta item as the best valid update is not valid, and re-constructing appcast items is discouraged. (The custom version comparator it uses is questionable too).
