### ISSUE TITLE
Switching a scene and triggering a source transition will sometimes break the source visibility state

### ISSUE THREAD

**Issue by Fenrirthviti** [obsproject/obs-studio#5291]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/odppsy7QYUhzTUWU

### Expected Behavior

Sources should not break visibility behavior when transitioning regardless of the order transitions are triggered in

### Current Behavior

Sources will sometimes break when a source transition is triggered during a normal scene transition, or vice versa. This causes the sources to behave irregularly, see the below two videos for examples of how it breaks:

https://pub.rachni.com/vid/2021-09-16_18-24-09.webm

and

https://pub.rachni.com/vid/2021-09-16_18-26-24.webm

### Steps to Reproduce

1. Create 2 or more scenes
2. Use "Add Existing" to add the same source to all scenes
3. Assign a show/hide transition to the source in all scenes
4. Assign a hotkey to show/hide the source in all scenes (I used the same hotkey for every action)
5. Replicate either of the following:
  a. Initiate a source transition by hitting the hotkey and then rapidly change scenes
  b. Initiate a scene transition and rapidly trigger a source transition by hitting the hotkey

### Anything else we should know?

It may take several attempts of mashing the hotkey and switching scenes rapidly to trigger, probably a race condition of some kind.

**Comment by 40wattrange** [comment]
Throwing this video here as far as my repro steps too.

https://www.youtube.com/watch?v=GIEryqtKQG4

**Comment by masterwindu69** [comment]
Hi. Will this be fixed in v28? I would love to use source transitions again without breaking the visibility state.

**Comment by PatTheMav** [comment]
@Fenrirthviti What's the definition of "broken" here, because so far the only thing I was able to replicate was that the different "show" transitions are combined, which looks visually jarring but didn't "break" the sources.

**Comment by itroy187** [comment]
@PatTheMav The source will stop showing its content (videos dont play, images aren't displayed) until OBS is restarted. At least that was the case when I was reproducing this behavior in OBS27. Never tried it in v28 (I'm still on v27).

**Comment by PatTheMav** [comment]
Then the issue didn't occur to me at all on macOS, might require someone reproducing on Windows and/or Linux.

**Comment by Fenrirthviti** [comment]
I can't seem to replicate in 28 on Windows either. Seems to have been fixed, going to go ahead and close this. If someone else can replicate on 28, we can reopen.

**Comment by itroy187** [comment]
@Fenrirthviti Was able to replicate this as described [here](https://github.com/obsproject/obs-studio/issues/6397) in v28 as well.. Unfortunately it's not fixed.

https://user-images.githubusercontent.com/6821126/193013772-cf7eb5aa-47d0-436e-9e50-d900267ed88f.mp4

**Comment by masterwindu69** [comment]
@Fenrirthviti The issue persists in OBS 28. Tested with clean install. I used the steps described to reproduce.

**Comment by PatTheMav** [comment]
Maybe I'm reproducing this wrong, because I can see no issues:


https://user-images.githubusercontent.com/9436503/195112826-07d8fe35-da15-470b-96c8-ecd00c2529b8.mov

**Comment by itroy187** [comment]
@PatTheMav Hmm.. interesting. I have a slightly different way to reproduce it described [here](https://github.com/obsproject/obs-studio/issues/6397). This way I'm able to reproduce the issue on both of my two computers.
