### ISSUE TITLE
libx264rgb broken after OBS Version 28.

### ISSUE THREAD

**Issue by MEKKERMB** [obsproject/obs-studio#7345]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/WJYoEE6b10n-fLO0

### Expected Behavior

The same behaviour dosen't happen with OBS 27.2.4.
**Mediainfo:** https://i.imgur.com/fqxeSCH.png
**mpv:** https://i.imgur.com/LOG9iVd.png
**Log:** https://obsproject.com/logs/h0GjkxmOZyZluDkX

### Current Behavior

Currently in OBS 28, when trying to record with libx264rgb the footage ends up being in yuv444p Format as reported by Mediainfo and mpv media player.
**Mediainfo:** https://i.imgur.com/W5cs2bJ.png
**mpv:** https://i.imgur.com/u5Pyy8c.png
**Log:** https://obsproject.com/logs/WJYoEE6b10n-fLO0

### Steps to Reproduce

**This guide from a Reddit post:** https://www.reddit.com/r/obs/comments/c1798j/comment/erbpal6/?utm_source=share&utm_medium=web2x&context=3

**Comment by flaeri** [comment]
works fine with UTvideo in custom ffmpeg output, so perhaps this would be better named "libx264rgb broken".

**Comment by MEKKERMB** [comment]
> works fine with UTvideo in custom ffmpeg output, so perhaps this would be better named "libx264rgb broken".

Okay, good to know. I've changed the title as you suggested.

**Comment by ValZapod** [comment]
>footage ends up being in yuv444p Format as reported by Mediainfo

Which is correct, because the only way to differentiate between rgb and YUV444P is matrix. And it is not set to identity as it should be. Just update ffmpeg to support rgb encoding with nvenc. Who cares about libx264.

https://github.com/FFmpeg/FFmpeg/commit/7555d6f74ce4845383e9297fd0989059739af4c2


 As for this issue it is a known issue. Update to newer ffmpeg official https://github.com/BtbN/FFmpeg-Builds/releases

Sometimes you should remember that ffmpeg has a policy that only master is stable.

**Comment by flaeri** [comment]
@ValZapod I understand you believe that nvenc is superior for this usecase, but I dont personally think it's befitting to drop into an issue like this.

If you believe this (specific) issue is fixed upstream , please link to that instead, so that we can keep track of it, and close this once FFmpeg deps are updated. Thank you for your understanding.

**Comment by ValZapod** [comment]
This is very simple to fix. Change to

qp=0 preset=ultrafast colorspace=0

fixed. Same as in ffmpeg. 

>once FFmpeg deps are updated

I do no think you are using HEAD of master that is the recommended version until LTS is introduced.

**Comment by ValZapod** [comment]
It was fixed here: https://trac.ffmpeg.org/ticket/9132 (https://github.com/FFmpeg/FFmpeg/commit/2818b143929d86f6b67695b09bc7483da5cef434)

But there were 10 different issues around this after that.

**Comment by ValZapod** [comment]
And BTW, **LOL**, this is not best quality.

It does not look lossless. At all. Yes, I did output set to 4K.

**Comment by flaeri** [comment]
Thank you for the link to the ticket and commit.

I'd appreciate if we could stay on topic, and exclusively talk about things pertaining to the issue.

**Comment by ValZapod** [comment]
>things pertaining to the issue

But I fixed the issue. Just add colorspace=0 and you will not get the pink image, cause it is now tagged as Identity.

**Comment by ValZapod** [comment]
BTW, it craches two times while I was testing. Here are stacktraces: 
[crashonergb.txt](https://github.com/obsproject/obs-studio/files/9682564/crashonergb.txt)
[crashtworgb.txt](https://github.com/obsproject/obs-studio/files/9682565/crashtworgb.txt)

**Comment by Fenrirthviti** [comment]
We believe this should be resolved with the newer ffmpeg we ship. It also appears the issue is more with ffmpeg and expectation of setting correct params, which would fall in to unsupported territory with custom ffmpeg output and our stance on "best effort" for things there. Going to close this as we're reasonably sure the original issue is resolved.

**Comment by ValZapod** [comment]
Nope, it in fact the same issue, you need to set colorspace=0 in 29.0.

**Comment by Kotsuha** [comment]
I have the same problem. From the comments above it seems that it's fixed but I still don't know how to make libx264rgb work again (it used to work a long long time ago). By following [this post](https://obsproject.com/forum/threads/recording-in-rgb-color-space-broken.159354/), it works for me now. It might help someone else so I re-post it here.

> A workaround mentioned in the bug report is to add
> Code:
> ```
> colorspace=0
> ```
> to the Video Encoder Settings box in OBS, which will at least correctly flag the resulting h.264 video as RGB.

**Comment by sudoBash418** [comment]
I recently ran into this issue as well, but only realized after recording many hours of video.
I was able to mostly recover the files by using `ffmpeg` to change the h264 metadata:
```
ffmpeg -i bad-file.mkv -map 0:v -map 0:a -bsf:v h264_metadata='matrix_coefficients=0' recovered-file.mkv
```

In my experience, the recovered video is still degraded (looks similar to chroma subsampling), but it's much better than completely mangled colors.

**Comment by Kotsuha** [comment]
> I recently ran into this issue as well, but only realized after recording many hours of video. I was able to mostly recover the files by using `ffmpeg` to change the h264 metadata:
> 
> ```
> ffmpeg -i bad-file.mkv -map 0:v -map 0:a -bsf:v h264_metadata='matrix_coefficients=0' recovered-file.mkv
> ```
> 
> In my experience, the recovered video is still degraded (looks similar to chroma subsampling), but it's much better than completely mangled colors.

Thank you for sharing this. I just tried it with one of my broken files and it worked. I then tried it without re-encoding: 

```
ffmpeg -i "bad-file.mkv" -map 0:v -map 0:a -bsf:v h264_metadata='matrix_coefficients=0' -c:v copy -c:a copy "recovered-file.mkv"
```

I don't know how to examine if it's lossless, but from the file size it generated, and the time it costed, it seemed to work as expected.
