### ISSUE TITLE
Screen Capture freezes on Osx 13.0 Ventura

### ISSUE THREAD

**Issue by kvzonbr** [obsproject/obs-studio#7663]
### Operating System Info

Other

### Other OS

OSX 13 Ventura

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/KVcfUEkgE8jF711i

### Expected Behavior

after update to Osx 13 Venture, the screen capture freezes after a while, if I shut down the source and started again i works for a short while  tried changing to application capture and same result

### Current Behavior

after update to Osx 13 Venture, the screen capture freezes after a while, if I shut down the source and started again i works for a short while  tried changing to application capture and same result

if I toggle the screen (from my 2 monitors) works again 

### Steps to Reproduce

1. start stream with game open in full screen 
2. stream until screen capture freezes
3. Change the monitos on on screen capture o change to application capture to activate the source

### Anything else we should know?

after venture update I changed the screen capture to application capture and started the promble.

after I changed it back and it remained the same

**Comment by kvzonbr** [comment]
so far a work around is that I loaded the obsolete screen capture avoiding the freeze.

**Comment by gxalpha** [comment]
For tracking, I’ve had this happen to me.
So far I’ve been unable to reliably reproduce it, it can sometimes take up to an hour to freeze.

Doing anything to restart the session should fix it (toggling "Show Cursor" should be the least disruptive).

**Comment by gxalpha** [comment]
So, the behavior is:
Out of nowhere after 20-30 minutes, all ScreenCaptureKit sources freeze simultaneously.

For every source, I get these two messages:
```
2022-11-05 21:11:11.124954+0100 OBS[66316:4966727]  [ERROR] _SCStream_RemoteAudioQueueOperationHandlerWithError:710 Error received from the remote queue -16665
2022-11-05 21:11:11.124966+0100 OBS[66316:4966723]  [ERROR] _SCStream_RemoteVideoQueueOperationHandlerWithError:662 Error received from the remote queue -16665
```

I can reproduce this pretty reliably when capturing StarCraft 2. I tried but so far failed to reproduce it with other apps.

Also I'm unsure if this is a duplicate of #7237. The symptoms look similar but error messages don't match up.

**Comment by kvzonbr** [comment]
> So, the behavior is: Out of nowhere after 20-30 minutes, all ScreenCaptureKit sources freeze simultaneously.
> 
> For every source, I get these two messages:
> 
> ```
> 2022-11-05 21:11:11.124954+0100 OBS[66316:4966727]  [ERROR] _SCStream_RemoteAudioQueueOperationHandlerWithError:710 Error received from the remote queue -16665
> 2022-11-05 21:11:11.124966+0100 OBS[66316:4966723]  [ERROR] _SCStream_RemoteVideoQueueOperationHandlerWithError:662 Error received from the remote queue -16665
> ```
> 
> I can reproduce this pretty reliably when capturing StarCraft 2. I tried but so far failed to reproduce it with other apps.
> 
> Also I'm unsure if this is a duplicate of #7237. The symptoms look similar but error messages don't match up.

Actually my issue is also presented on StarCraft 2 also, With the old screen capture works fine for now as a work around, so I can keep streaming.

**Comment by HiroiSekai** [comment]
^ This is my thread, but I'm gonna also chime in here and note that it looks to be a widespread common issue. At the moment, unless you're capturing content from a separate camera or capture card, OBS on Mac is unusable as a streamer with these freezes. I've done about 3 streams in a row now where I'll be playing a game, and then silently it freezes and my chat has to point it out to me, or I'm focused on the game.

This isn't just for games either, it's screen capture in any capacity it seems. If I want to share a browser window to surf a website on stream, if I want to play music from a separate player, etc. If it's not an external device capture, it'll freeze anywhere between 1 minute and about 30 minutes.

I really hope this can be fixed and isn't another Apple-implemented hurdle. I could always try running OBS through Parallels on my Mac, but OBS on Windows doesn't like me for a whole other can of worms, and I really really prefer not having to even touch Windows myself.

**Comment by Developer-Ecosystem-Engineering** [comment]
We are looking into it

**Comment by HiroiSekai** [comment]
Thanks for the update, I shall patiently wait.

**Comment by Developer-Ecosystem-Engineering** [comment]
Could you confirm this is resolved in the latest seed builds of macOS 13? Thats 22C5050e.

**Comment by HiroiSekai** [comment]
I put myself back on the macOS beta for that build, I can confirm the issue is still the same.

**Comment by Developer-Ecosystem-Engineering** [comment]
Thanks @HiroiSekai, looking again on our end.

**Comment by HiroiSekai** [comment]
Many thanks, I'll keep checking if I can help with any testing. 👍

**Comment by Chromagram** [comment]
Would that fully fix the issue, or would there still be that split moment of it restoring screen recording where both video and audio chops out? Considering how often it does this, it'd be nice as a quick band-aid but not long-term viable for a streamer and their audience if the split moment chopping is indeed going to occur.

Just want to make sure, thanks for looking more into this.

**Comment by effolkronium** [comment]
The split moment is more acceptable issue then permanent hang

While @PatTheMav speaks with Apple, this workaround would be great for me, because I need to record online lectures of my University

**Comment by gxalpha** [comment]
> Let's implement a workaround. If log with error appears, reset cursor setting. It'll trigger restoration of screen recording

Let's not do that. This would be a giant hack and likely also require lots of code in places where it's not supposed to be.

[As stated before](https://github.com/obsproject/obs-studio/issues/7663#issuecomment-1292870195), this doesn't happen with the old sources, which are still available in the "Deprecated" menu. Please use those as a workaround.

**Comment by Chromagram** [comment]
Yeah, it sucks right now, but I agree that waiting for a permanent solution is better. The Mac is insanely locked down compared to Windows, and workarounds (from my experience) just stick on a band-aid that another restriction comes along to rip it off. Getting a permanent fix is the right solution. Do it right, and Apple's much more rock solid stability over Windows will ensure the fix actually stays for the long term and not stab a new hole into the leaking wall like Windows updates will.

Until then, I'll stick with the deprecated old sources if that works. I always forget to look in that folder. Thanks for the reminder.

**Comment by Developer-Ecosystem-Engineering** [comment]
The latest build [22C5059b](https://developer.apple.com/news/releases/?id=12012022c) should resolve the remaining scenarios impacting folks. If you see failures on that build, log a [Feedback](https://developer.apple.com/bug-reporting/) with the relevant details.

**Comment by effolkronium** [comment]
@Developer-Ecosystem-Engineering just curious where did you found this info ? The beta 4 release notes does not contain any hints to replayd possible fixes

**Comment by effolkronium** [comment]
After updating to the latest MacOS release 13.1 and recording a few university lectures I can confirm - the issue is fixed for me, no freezes was observed

**Comment by Developer-Ecosystem-Engineering** [comment]
Excellent @effolkronium, it would be good for other reporters to confirm, but we are fairly confident this should be resolved now on the platforms side.

**Comment by kvzonbr** [comment]
just updated to 13.1 and tested it a few hours with SC2 (just obs open and capturing no stream or recording), so far everything it's ok, tonight i'll stream to test further. thanks everyone

**Comment by Chromagram** [comment]
Same here, I haven't streamed it yet out of concern for how my last few streams froze up, but just letting it sit with no stream/recording and it's been doing okay so far.

Thanks for confirming the fix.

**Comment by PatTheMav** [comment]
Seems to be fixed by the 13.1 update then - will close this for now, if the issue persists we can reopen or look into it via a new issue.
