### ISSUE TITLE
macOS Screen Sharing Doesn't Stop When OBS Is Quit

### ISSUE THREAD

**Issue by Avakining** [obsproject/obs-studio#9850]
### Operating System Info

macOS 14

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/nG1zKB8ROdmNwH3W

### Expected Behavior

Screen Sharing should stop when OBS is quit

### Current Behavior

The Screen Sharing button in the Menu Bar still exists, even after OBS is quit

### Steps to Reproduce

1. Open OBS
2. Ensure there is an extant scene with a screen capture source
3. Quit OBS
4. Notice that the purple Screen Sharing button still appears in the Menu Bar

### Anything else we should know?

Note that no OBS process is running, but the Screen Sharing button is still saying that OBS is sharing the screen.
<img width="1026" alt="Screenshot 2023-11-13 at 10 49 21" src="https://github.com/obsproject/obs-studio/assets/25210618/71bf550f-e660-445e-aee7-bd8cc1266c7a">
The only way I've found to make the button go away after opening OBS at any point is to restart the entire computer.

**Comment by AndreaCicca** [comment]
Same situation

**Comment by yllekz** [comment]
Your specific macOS version is?
Update your Mac to 14.1?
I'm on 14.1 and didn't encounter this.

**Comment by AndreaCicca** [comment]
> Your specific macOS version is? Update your Mac to 14.1? I'm on 14.1 and didn't encounter this.

I am on 14.1 (23B74)

**Comment by jcm93** [comment]
This should be fixed by one of #9803 or macOS 14.2, or possibly both.

**Comment by Avakining** [comment]
> Your specific macOS version is? Update your Mac to 14.1? I'm on 14.1 and didn't encounter this.

I'm on macOS 14.1.1

**Comment by gxalpha** [comment]
As noted above this is worked around on current master, and the underlying macOS bug fixed with macOS 14.2

**Comment by brianp** [comment]
I'm on macOS 14.2 (23C64), and OBS 30.0.2 and this issue persists.

**Comment by humblecoder** [comment]
> I'm on macOS 14.2 (23C64), and OBS 30.0.2 and this issue persists.

Same.  Literally no other "streaming" app I've used has this problem.

**Comment by gxalpha** [comment]
Contrary to what we believed before this is not fixed in macOS 14.2, but as stated earlier it already worked around on the current OBS master branch (see https://github.com/obsproject/obs-studio/pull/9803), so if this highly important to you you're welcome to test a nightly build (and, if using that nightly build the issue *still* persists please open a new issue).

Though again the underlying bug is in macOS. OBS can't be sharing anything at this point because, you know, it's not running anymore.

**Comment by jcm93** [comment]
> Contrary to what we believed before this is not fixed in macOS 14.2, but as stated earlier it is already worked around on the current OBS master branch (see #9803), so if this highly important to you you're welcome to test a nightly build (and, if using that nightly build the issue _still_ persists please open a new issue).
> 
> Though again the underlying bug is in macOS. OBS can't be sharing anything at this point because, you know, it's not running anymore.

#9803 did make it into 30.0.2. So I'm thinking these are indeed legitimate reports.

For my part, I haven't had a ton of time actually using OBS of late, but I have noticed that the capture indicator will linger for 20-30 seconds after closing OBS sometimes. I haven't had it linger longer than that. I'd need to do more digging to see if I can find other situations where this occurs.

**Comment by gxalpha** [comment]
> https://github.com/obsproject/obs-studio/pull/9803 did make it into 30.0.2.

I missed that.
In that case, someone affected by the bug would have to create a proper new report, new log file, Steps to Reproduce, etc.

**Comment by dileeparanawake** [comment]
> Same issue Mac OS 14.2.1 (23C71) / OBS 30.0.2 64 bit (M1 Mac)

Update - I noticed that after quitting OBS and then using activity monitor and force quitting `replayd` , when I restarted OBS, screen sharing stopped on OBS quit too (so resolving issue).

**Comment by KrisTemmerman** [comment]
> > Same issue Mac OS 14.2.1 (23C71) / OBS 30.0.2 64 bit (M1 Mac)
> 
> Update - I noticed that after quitting OBS and then using activity monitor and force quitting `replayd` , when I restarted OBS, screen sharing stopped on OBS quit too (so resolving issue).

This worked for me as well

**Comment by jcm93** [comment]
If anyone still experiencing this issue has a reliable way to reproduce it, with steps, that would be more helpful than "me too"s on here. The steps from the OP here should not be triggering the issue.

I personally have also continued to run into the lingering capture indicator on 14.4 / 30.1, but I don't have consistent steps to reproduce the behavior.

**Comment by natsunoshion** [comment]
> > Same issue Mac OS 14.2.1 (23C71) / OBS 30.0.2 64 bit (M1 Mac)
> 
> Update - I noticed that after quitting OBS and then using activity monitor and force quitting `replayd` , when I restarted OBS, screen sharing stopped on OBS quit too (so resolving issue).

Worked for me!
